apiVersion: v1
kind: ServiceAccount
metadata:
  name: dispatcher-sa
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pod-reader
  namespace: default
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: read-pods
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pod-reader
subjects:
- kind: ServiceAccount
  name: dispatcher-sa
  namespace: default
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dispatcher
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dispatcher
  template:
    metadata:
      labels:
        app: dispatcher
    spec:
      serviceAccountName: dispatcher-sa
      containers:
      - name: dispatcher
        image: demo/dispatcher:latest
        imagePullPolicy: IfNotPresent 
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: dispatcher
spec:
  selector:
    app: dispatcher
  ports:
  - port: 8080
    targetPort: 8080 